### ISSUE TITLE
API do tamojunto!

### ISSUE THREAD

**Issue by lucasferreira** [viniciusdlx/api-2gether#1]
Mister Xavier e sua gangue, APIzinha bacana rolou aqui. Sei o que o foco da disciplina é o app mobile mas fiz questão de dar uma moral aqui também. Vocês fazem um bom trabalho como dev, terão um baita futuro pela frente. Agradeço não só esta entrega como também a presença em sala de aula ao longo desse semestre, ficarei com saudades de todos vocês!

NestJS é sempre uma boa escolha, padrão MVC bem executado. Minha única sugestão seria quebrar a API em pedaços menores, principalmente os controllers. Sei que é um trabalho acadêmico e o foco não era a API em si, mas dava de ter feito um controller para agendamento, outro para itens e outro para estoque ;)

De resto ta bacana, valeu novamente 👊

**Comment by viniciusdlx** [comment]
Muito obrigado Mestre Lucas, seus ensinamentos sempre estarão conosco e suas dicas serão sempre bem vindas, e com elas pretendemos melhorar como dev e como pessoa!!
